const app = document.querySelector('#app');
const toast = document.querySelector('#toast');

const demo = {
  role: 'Cybersecurity Engineer', company: 'Northstar Systems', candidate: 'Maya Patel',
  resumeText: `MAYA PATEL\nSecurity-focused software engineer with 3 years of experience building backend services and security tooling.\n\nEXPERIENCE\nSecurity Engineering Intern — Vector Labs (2024–2025)\nBuilt Python automation for vulnerability triage and Linux server hardening. Created REST APIs with FastAPI and PostgreSQL for security findings.\n\nPROJECTS\nSentinel: Python and FastAPI service that collects audit events, validates incoming data, and creates investigation queues. Deployed using GitHub Actions.\n\nSKILLS\nPython, FastAPI, PostgreSQL, Linux, Git, Networking, REST APIs, React, Security monitoring, OWASP fundamentals`,
  jdText: `CYBERSECURITY ENGINEER — NORTHSTAR SYSTEMS\nBuild and secure cloud-native services used by enterprise customers.\n\nRequired: Python, Linux, REST API security, Docker, AWS, networking, security monitoring, SIEM experience, and 3+ years of relevant engineering experience.\nPreferred: FastAPI, PostgreSQL, incident response, Terraform.\nResponsibilities include designing secure services, improving observability, investigating alerts, and collaborating with platform engineering.`,
  requirements: [
    ['Python', 'Built Python automation for vulnerability triage and security tooling.', 'matched', 'Critical', 100],
    ['Linux', 'Hardened Linux servers during security engineering internship.', 'matched', 'Critical', 100],
    ['REST API security', 'FastAPI service validates incoming audit events; OWASP fundamentals listed.', 'partial', 'Critical', 72],
    ['Docker', '—', 'missing', 'Critical', 12],
    ['AWS', 'Cloud deployment not evidenced in the resume.', 'missing', 'Critical', 8],
    ['Networking', 'Networking is listed in technical skills.', 'matched', 'Important', 88],
    ['Security monitoring', 'Sentinel project collects audit events and creates investigation queues.', 'matched', 'Important', 84],
    ['SIEM experience', 'Security findings workflow is related, but no SIEM platform is named.', 'partial', 'Important', 48],
    ['FastAPI', 'Built REST APIs with FastAPI for security findings.', 'matched', 'Preferred', 100],
    ['PostgreSQL', 'Used PostgreSQL with FastAPI services.', 'matched', 'Preferred', 92],
    ['Incident response', 'Vulnerability triage is relevant but formal incident response is not stated.', 'partial', 'Preferred', 42],
    ['Terraform', '—', 'missing', 'Secondary', 0]
  ],
  questions: [
    ['Technical', 'How would you secure a REST API exposed to the public internet?', 'The role calls for secure services and API security.', 'FastAPI service with input validation.', 'Authentication, authorization, rate limiting, input validation, audit logs.'],
    ['Project-based', 'Walk us through how Sentinel turns audit events into an investigation queue.', 'Tests whether you can explain the security project listed in your resume.', 'Sentinel project.', 'Data validation, event schemas, failure modes, prioritisation.'],
    ['Gap-focused', 'How would you package and deploy your FastAPI service on AWS?', 'Docker and AWS are critical requirements without direct resume evidence.', 'FastAPI experience is a relevant foundation.', 'Containers, IAM, secrets management, network boundaries, logging.'],
    ['Role-specific', 'What signals would you use to investigate an anomalous authentication alert?', 'The JD requires security monitoring and alert investigation.', 'Vulnerability triage and audit-event work.', 'Baseline behavior, telemetry, triage, escalation, response notes.'],
    ['Behavioral', 'Tell us about a time you balanced a delivery deadline with a security concern.', 'The role collaborates with platform engineering.', 'Security engineering internship.', 'Risk framing, alternatives, stakeholder communication, outcome.']
  ]
};

const state = { page: 'landing', theme: localStorage.getItem('careerlens-theme') || 'light', analysis: null, filter: 'all', selected: 0, processing: 0, resume: null, jd: null };
const nav = [['overview','Overview'], ['requirements','Requirements'], ['skills','Skills & gaps'], ['interview','Interview'], ['comparison','Compare'], ['guide','Preparation']];

function icon(name, size = 18) {
  const paths = { arrow:'M5 12h14m-6-6 6 6-6 6', upload:'M12 16V4m-4 4 4-4 4 4M5 20h14', sun:'M12 3v2m0 14v2m9-9h-2M5 12H3m15.36-6.36-1.42 1.42M7.05 16.95l-1.41 1.41m0-12.72 1.41 1.42m9.9 9.9 1.42 1.41', moon:'M20.5 14.5A8.5 8.5 0 1 1 9.5 3.5a6.7 6.7 0 0 0 11 11Z', download:'M12 3v12m-5-5 5 5 5-5M5 21h14', check:'m5 12 4 4L19 6', file:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6', menu:'M4 6h16M4 12h16M4 18h16', close:'M6 6l12 12M18 6 6 18', chevron:'m9 18 6-6-6-6', info:'M12 8h.01M11 12h1v4h1M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Z' };
  return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name] || paths.file}"/></svg>`;
}
const title = (number, label, heading, copy='') => `<div class="section-title"><span>${number}</span><div><p>${label}</p><h2>${heading}</h2>${copy ? `<small>${copy}</small>` : ''}</div></div>`;
const status = value => `<span class="status ${value}"><i></i>${value.replace('_',' ')}</span>`;
const score = () => state.analysis?.score ?? 82;
function toastMessage(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2800); }
function setPage(page) { state.page = page; window.scrollTo({ top: 0, behavior: 'smooth' }); renderApp(); }

function renderApp() {
  document.documentElement.dataset.theme = state.theme;
  const views = { landing: landingView, setup: setupView, processing: processingView, overview: overviewView, requirements: requirementsView, skills: skillsView, interview: interviewView, comparison: comparisonView, guide: guideView, settings: settingsView };
  app.innerHTML = views[state.page]();
  bind();
}

function landingView() { return `<main class="landing">
  <header class="landing-nav"><button class="wordmark" data-page="landing">CAREER<span>LENS</span></button><div class="nav-actions"><button class="text-btn" data-page="settings">Settings</button><button class="icon-btn" data-theme aria-label="Toggle color theme">${icon(state.theme === 'dark' ? 'sun' : 'moon')}</button><button class="button dark" data-page="setup">Analyze a role ${icon('arrow')}</button></div></header>
  <section class="hero"><div class="hero-copy"><p class="eyebrow">ROLE INTELLIGENCE / 01</p><h1>Know how your resume<br>holds up against<br><em>the role.</em></h1><p class="lede">Compare your resume with the exact requirements of a job. Find what matches, what is missing, and what to prepare before the interview.</p><div class="hero-buttons"><button class="button dark" data-page="setup">Analyze a role ${icon('arrow')}</button><button class="button outline" data-demo>See a sample analysis</button></div><p class="micro">PRIVATE WORKSPACE &nbsp;·&nbsp; EXPLAINABLE SCORING &nbsp;·&nbsp; NO HIRING PREDICTIONS</p></div>
  <div class="hero-instrument"><div class="instrument-top"><span>ANALYSIS / 001</span><span class="live"><i></i> COMPLETE</span></div><div class="instrument-role"><p>TARGET ROLE</p><h3>Cybersecurity<br>Engineer</h3><span>Northstar Systems</span></div><div class="instrument-score"><div class="ring"><b>82</b><small>/100</small></div><div><p>ALIGNMENT</p><h4>Strong requirement coverage</h4><small>Evidence mapped across 12 requirements.</small></div></div><div class="mini-bars"><span>Python <i style="width:100%"></i><b>100</b></span><span>API security <i style="width:72%"></i><b>72</b></span><span>Docker <i style="width:12%"></i><b>12</b></span></div><div class="instrument-foot"><span>7 MATCHED</span><span>3 PARTIAL</span><span>2 MISSING</span></div></div></section>
  <section class="process-section"><div>${title('02','THE METHOD','Evidence, not empty promises','A structured route from documents to focused preparation.')}</div><div class="method-grid"><article><b>01</b><h3>Read the role</h3><p>Extract the role’s skills, responsibilities, and qualifications.</p></article><article><b>02</b><h3>Map the proof</h3><p>Pair requirements with concrete evidence found in your resume.</p></article><article><b>03</b><h3>Prepare with intent</h3><p>Prioritise gaps and build an interview workbook around them.</p></article></div></section>
  <section class="feature-band"><p class="eyebrow">BUILT FOR THE CONVERSATION AFTER SUBMISSION</p><div class="feature-grid"><h2>Turn a job description into a practical preparation plan.</h2><ul><li><b>Requirement matrix</b><span>Matched, partial, and missing — with evidence.</span></li><li><b>Explainable alignment</b><span>A score with visible inputs, never a hiring forecast.</span></li><li><b>Interview workbook</b><span>Questions tied to the role and your stated experience.</span></li></ul></div></section>
  <footer><span>CAREERLENS / 2026</span><span>Your documents are used only for this analysis.</span><button data-page="setup">Start an analysis ${icon('arrow')}</button></footer></main>`; }

function setupView() { const r = state.resume, j = state.jd; return shell('setup', `<section class="page-heading"><p class="eyebrow">ANALYSIS SETUP / NEW RUN</p><h1>Start a role analysis</h1><p>Provide the documents. We’ll validate the text before mapping evidence to requirements.</p></section><section class="workspace"><div class="doc-panel">${documentInput('resume','Your resume','PDF · DOCX · TXT', r, 'Resume')}</div><div class="doc-panel">${documentInput('jd','Target role','Paste a JD or upload PDF · DOCX · TXT', j, 'Job description')}</div></section><div class="privacy-note">${icon('info',16)} Your documents are used only for this analysis. We don’t make a prediction about hiring outcomes.</div><div class="setup-footer"><div><span class="mono">INPUT STATUS</span><b>${r && j ? 'Both documents ready for validation' : 'Waiting for two documents'}</b></div><button class="button dark" data-begin ${r && j ? '' : 'disabled'}>Begin analysis ${icon('arrow')}</button></div>`); }

function documentInput(kind, heading, accepted, document, label) { return `<div class="doc-heading"><div><p class="eyebrow">${kind === 'resume' ? '01 / CANDIDATE' : '02 / ROLE'}</p><h2>${heading}</h2></div>${document ? status('matched') : '<span class="mono muted">NOT ADDED</span>'}</div>${document ? `<div class="document-ready">${icon('file',26)}<div><b>${document.name}</b><small>${document.size} · ${document.format}</small></div><button class="text-btn" data-clear="${kind}">Replace</button></div><div class="extract-preview"><span class="mono">EXTRACTED PREVIEW</span><p>${escapeHTML(document.text.slice(0, 250))}${document.text.length > 250 ? '…' : ''}</p></div>${document.error ? `<div class="validation-error"><b>INPUT ERROR</b><p>${document.error}</p><small>Upload a text-readable document with meaningful ${kind === 'resume' ? 'candidate information' : 'role requirements'}.</small></div>` : ''}` : `<label class="upload-area" for="${kind}-file">${icon('upload',24)}<b>Upload ${label}</b><span>${accepted}</span><input id="${kind}-file" data-file="${kind}" type="file" accept=".pdf,.docx,.txt,text/plain,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document"></label>${kind === 'jd' ? `<label class="paste-label">OR PASTE THE JOB DESCRIPTION<textarea data-jd-text placeholder="Paste the full role description here…"></textarea></label>` : ''}`}`; }

function processingView() { const stages = ['Input intake','Text extraction','Entity & skill extraction','Requirement mapping','Resume / JD comparison','Gap analysis','Interview generation']; return shell('processing', `<section class="processing-wrap"><div><p class="eyebrow">ANALYSIS RUN / 001</p><h1>Building the evidence map</h1><p class="lede">Each step turns document text into an explainable preparation plan.</p></div><ol class="timeline">${stages.map((s,i) => `<li class="${i < state.processing ? 'complete' : i === state.processing ? 'running' : ''}"><b>${String(i+1).padStart(2,'0')}</b><span>${s}</span><em>${i < state.processing ? 'COMPLETE' : i === state.processing ? 'RUNNING' : 'QUEUED'}</em></li>`).join('')}</ol><p class="processing-caption">${['Validating source documents','Extracting readable text','Identifying skills and evidence','Mapping role requirements','Comparing evidence','Ranking preparation gaps','Assembling interview workbook'][state.processing] || 'Opening analysis'}</p></section>`); }

function shell(active, content) { return `<div class="app-shell"><aside><button class="wordmark" data-page="landing">CAREER<span>LENS</span></button><p class="sidebar-label">WORKSPACE</p><nav>${nav.map(([id,label]) => `<button class="side-link ${active===id?'active':''}" data-page="${id}"><i>${String(nav.findIndex(x=>x[0]===id)+1).padStart(2,'0')}</i>${label}</button>`).join('')}</nav><div class="side-bottom"><button class="side-link ${active==='setup'?'active':''}" data-page="setup"><i>+</i>New analysis</button><button class="side-link ${active==='settings'?'active':''}" data-page="settings"><i>·</i>Settings</button></div></aside><main class="product"><header class="product-bar"><button class="mobile-menu" data-mobile-menu>${icon('menu')}</button><span class="mono">ANALYSIS / 001</span><div><span class="run-status"><i></i> COMPLETE</span><button class="icon-btn" data-theme aria-label="Toggle color theme">${icon(state.theme === 'dark' ? 'sun' : 'moon')}</button><button class="export-btn" data-export>${icon('download',16)} <span>Export report</span></button></div></header>${content}</main></div>`; }

function overviewView() { const a = getAnalysis(); return shell('overview', `<section class="role-header"><div><p class="eyebrow">TARGET ROLE / ${a.company.toUpperCase()}</p><h1>${a.role}</h1><p>Analysis completed ${new Intl.DateTimeFormat('en',{month:'short',day:'2-digit',year:'numeric'}).format(new Date())} · Resume + job description</p></div><button class="button outline" data-page="requirements">Open requirement matrix ${icon('arrow')}</button></section><section class="score-layout"><div class="score-block"><p class="eyebrow">01 / RESUME-TO-JD ALIGNMENT</p><div class="score-number"><strong>${a.score}</strong><span>/100</span></div><h2>Strong requirement coverage</h2><p>Alignment reflects the degree to which resume evidence corresponds to this JD. It is not a prediction of hiring outcome.</p></div><div class="breakdown"><p class="eyebrow">SCORE CONTRIBUTION</p>${a.breakdown.map(x=>`<div><span>${x[0]}</span><b>${x[1]}/${x[2]}</b><i><em style="width:${x[1]/x[2]*100}%"></em></i></div>`).join('')}<footer><span>TOTAL</span><b>${a.score}/100</b></footer></div></section><section class="overview-grid"><div>${title('02','REQUIREMENT COVERAGE','Evidence at a glance')}<div class="coverage"><div><b>${a.counts.matched}</b><span>Matched</span></div><div><b>${a.counts.partial}</b><span>Partial</span></div><div><b>${a.counts.missing}</b><span>Missing</span></div></div></div><div>${title('03','PRIORITY GAPS','Prepare these first')}<ol class="priority-list">${a.requirements.filter(x=>x.status!=='matched').slice(0,3).map((x,i)=>`<li><b>${String(i+1).padStart(2,'0')}</b><span>${x.name}<small>${x.priority} · ${x.status} evidence</small></span><i></i></li>`).join('')}</ol></div></section><section class="table-section">${title('04','REQUIREMENT MATRIX','Where the resume meets the role','A compact read of every extracted requirement.')} ${requirementsTable(a.requirements.slice(0,6))}<button class="text-btn row-link" data-page="requirements">View all requirements ${icon('arrow')}</button></section><section class="interview-preview">${title('05','INTERVIEW PREVIEW','Questions worth preparing')}<div class="question-preview">${a.questions.slice(0,2).map((q,i)=>`<article><span>Q${String(i+1).padStart(2,'0')} / ${q.category}</span><h3>${q.question}</h3><p>${q.reason}</p></article>`).join('')}</div><button class="button dark" data-page="interview">Open interview workbook ${icon('arrow')}</button></section>`); }

function requirementsTable(rows) { return `<div class="table-wrap"><table><thead><tr><th>Requirement</th><th>Resume evidence</th><th>Status</th><th>Priority</th></tr></thead><tbody>${rows.map((x,i)=>`<tr data-requirement="${i}"><td><b>${x.name}</b><small>${x.coverage}% coverage</small></td><td>${x.evidence}</td><td>${status(x.status)}</td><td><span class="priority ${x.priority.toLowerCase()}">${x.priority}</span></td></tr>`).join('')}</tbody></table></div>`; }

function requirementsView() { const a=getAnalysis(), visible = state.filter === 'all' ? a.requirements : a.requirements.filter(x=>x.status===state.filter); return shell('requirements', `<section class="page-heading compact"><p class="eyebrow">02 / REQUIREMENT COVERAGE</p><h1>Requirement matrix</h1><p>Every role requirement is mapped to stated resume evidence. Select a row to inspect the match.</p></section><div class="filter-bar">${['all','matched','partial','missing'].map(f=>`<button class="${state.filter===f?'active':''}" data-filter="${f}">${f==='all'?'All':f[0].toUpperCase()+f.slice(1)} <b>${f==='all'?a.requirements.length:a.counts[f]}</b></button>`).join('')}</div>${requirementsTable(visible)}<section class="note-block"><b>HOW TO READ THIS MATRIX</b><p>“Matched” means the resume provides direct evidence. “Partial” means related evidence exists but does not fully support the requirement. “Missing” means no evidence was found in the current document.</p></section>`); }

function skillsView() { const a=getAnalysis(), groups=[['Matched skills','Skills clearly supported by resume evidence','matched'],['Partial matches','Related but incomplete resume evidence','partial'],['Missing requirements','No evidence in the current resume','missing']]; return shell('skills', `<section class="page-heading compact"><p class="eyebrow">03 / SKILLS & GAPS</p><h1>What is proved, and what needs preparation</h1><p>Gaps are ranked by their relevance to this specific role, not by a generic skills list.</p></section><div class="skill-columns">${groups.map(([h,c,s])=>`<section class="skill-group ${s}"><p class="eyebrow">${s.toUpperCase()} / ${a.counts[s]}</p><h2>${h}</h2><p>${c}</p>${a.requirements.filter(x=>x.status===s).map(x=>`<article><div><b>${x.name}</b><span class="priority ${x.priority.toLowerCase()}">${x.priority}</span></div><p>${x.evidence}</p><div class="skill-line"><i style="width:${x.coverage}%"></i><small>${x.coverage}%</small></div></article>`).join('')}</section>`).join('')}</div><section class="gap-action">${title('04','PREPARATION PRIORITY','Close the most consequential gaps')}<div>${a.requirements.filter(x=>x.status==='missing'||x.status==='partial').slice(0,3).map((x,i)=>`<article><b>${String(i+1).padStart(2,'0')}</b><div><h3>${x.name}</h3><p>${gapCopy(x.name)}</p></div><button class="text-btn" data-page="interview">Prepare ${icon('arrow')}</button></article>`).join('')}</div></section>`); }

function comparisonView() { const a=getAnalysis(), selected=a.requirements[state.selected] || a.requirements[0]; return shell('comparison', `<section class="page-heading compact"><p class="eyebrow">04 / DOCUMENT COMPARISON</p><h1>Resume vs job description</h1><p>Select a requirement to trace it back to the evidence in the source documents.</p></section><div class="comparison-controls">${a.requirements.map((x,i)=>`<button data-select="${i}" class="${state.selected===i?'active':''}">${x.name} ${status(x.status)}</button>`).join('')}</div><section class="comparison-grid"><article><div class="doc-strip"><span>YOUR RESUME</span><span>EXTRACTED TEXT</span></div><p>${highlightText(a.resumeText, selected.name)}</p></article><article><div class="doc-strip"><span>JOB DESCRIPTION</span><span>EXTRACTED TEXT</span></div><p>${highlightText(a.jdText, selected.name)}</p></article></section><section class="evidence-result"><div><p class="eyebrow">CURRENT REQUIREMENT</p><h2>${selected.name}</h2><p>${selected.evidence}</p></div><div>${status(selected.status)}<p><b>Coverage ${selected.coverage}%</b><br>Priority: ${selected.priority}</p></div></section>`); }

function interviewView() { const a=getAnalysis(); return shell('interview', `<section class="page-heading compact"><p class="eyebrow">05 / INTERVIEW PREPARATION</p><h1>Interview workbook</h1><p>A structured set of questions created from this role, your projects, and your gaps.</p></section><div class="question-list">${a.questions.map((q,i)=>`<article class="question-card"><div class="question-index">Q${String(i+1).padStart(2,'0')}<span>${q.category}</span></div><div><h2>${q.question}</h2><div class="question-meta"><section><b>WHY THIS MATTERS</b><p>${q.reason}</p></section><section><b>YOUR EVIDENCE</b><p>${q.evidence}</p></section><section><b>PREPARE</b><p>${q.prepare}</p></section></div><div class="prep-actions"><button data-prepared="${i}" class="text-btn">Mark familiar ${icon('check',16)}</button><button class="text-btn" data-page="skills">Review gap ${icon('arrow')}</button></div></div></article>`).join('')}</div>`); }

function guideView() { const a=getAnalysis(); return shell('guide', `<section class="page-heading compact"><p class="eyebrow">06 / PREPARATION GUIDE</p><h1>A focused plan for the conversation ahead</h1><p>Use this as a working checklist. It separates resume evidence from suggested preparation.</p></section><div class="guide-grid"><section><p class="eyebrow">WHAT TO EXPLAIN</p><h2>Lead with existing proof</h2>${a.requirements.filter(x=>x.status==='matched').slice(0,4).map(x=>`<article><b>${x.name}</b><p>${x.evidence}</p></article>`).join('')}</section><section><p class="eyebrow">WHAT TO REVISE</p><h2>Close the role-specific gaps</h2>${a.requirements.filter(x=>x.status!=='matched').slice(0,4).map(x=>`<article><b>${x.name}</b><p>${gapCopy(x.name)}</p></article>`).join('')}</section></div><section class="practice-box"><span class="mono">PRACTICE SESSION / 30 MINUTES</span><h2>Explain one project, then defend one technical decision.</h2><p>Start with Sentinel. Prepare a concise deployment design that addresses Docker, AWS, access control, secrets, logs, and alert investigation.</p><button class="button dark" data-page="interview">Practice questions ${icon('arrow')}</button></section>`); }

function settingsView() { return shell('settings', `<section class="page-heading compact"><p class="eyebrow">WORKSPACE SETTINGS</p><h1>How CAREERLENS works</h1><p>A document analysis workspace designed to keep its reasoning inspectable.</p></section><section class="settings-list"><article><div><b>Appearance</b><p>Choose a reading environment that suits your workspace.</p></div><button class="button outline" data-theme>${state.theme === 'dark' ? 'Use light theme' : 'Use dark theme'}</button></article><article><div><b>Document handling</b><p>Documents remain in this browser session for the current analysis. Loading a new analysis replaces them.</p></div><span class="mono">SESSION ONLY</span></article><article><div><b>Scoring method</b><p>Alignment combines skills, experience, qualifications, and requirement coverage. It is never a hiring prediction.</p></div><span class="mono">EXPLAINABLE</span></article></section><section class="note-block"><b>DEMO MODE</b><p>This demo is fully deterministic and uses no external AI service. The structure is ready to connect a parser and generation provider behind the analysis workflow.</p></section>`); }

function getAnalysis() { if (state.analysis) return state.analysis; return buildAnalysis(demo.resumeText, demo.jdText, demo); }
function buildAnalysis(resumeText, jdText, source=demo) { const r = source.requirements.map(([name,evidence,status,priority,coverage])=>({name,evidence,status,priority,coverage})); const counts={matched:r.filter(x=>x.status==='matched').length,partial:r.filter(x=>x.status==='partial').length,missing:r.filter(x=>x.status==='missing').length}; const score=Math.round(r.reduce((sum,x)=>sum+x.coverage,0)/r.length); return { ...source, resumeText, jdText, requirements:r, counts, score, breakdown:[['Skills alignment',Math.round(score*.40),40],['Experience alignment',Math.round(score*.20),20],['Qualification alignment',Math.round(score*.18),20],['Requirement coverage',Math.round(score*.22),20]], questions:source.questions.map(([category,question,reason,evidence,prepare])=>({category,question,reason,evidence,prepare})) }; }
function gapCopy(name) { return ({Docker:'Practise containerising a small FastAPI service and describing its runtime boundaries.',AWS:'Learn a safe AWS deployment pattern: IAM, VPC boundaries, secrets, logs, and monitoring.', 'REST API security':'Be ready to explain authentication, authorization, validation, rate limits, and audit logging.', 'SIEM experience':'Understand the alert lifecycle, enrichment, correlation, and escalation workflow.', 'Incident response':'Review triage, containment, evidence preservation, and post-incident communication.', Terraform:'Understand infrastructure-as-code basics and how changes are reviewed.'})[name] || 'Connect this requirement to a concrete preparation example.'; }
function escapeHTML(value) { return value.replace(/[&<>'"]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function highlightText(text, term) { const escaped=escapeHTML(text); const safe=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); return escaped.replace(new RegExp(`(${safe})`,'ig'),'<mark>$1</mark>'); }

async function parseFile(file) { const format=file.name.split('.').pop().toUpperCase(); if (!['PDF','DOCX','TXT'].includes(format)) return {error:'This file type is not supported.',name:file.name,size:prettySize(file.size),format,text:''}; let text=''; try { if(format==='TXT') text=await file.text(); else { const raw=new TextDecoder('utf-8',{fatal:false}).decode(await file.arrayBuffer()); text=raw.replace(/[^\x20-\x7E\n]/g,' ').replace(/\s+/g,' '); } } catch { return {error:'We could not read this document.',name:file.name,size:prettySize(file.size),format,text:''}; } if (text.trim().length < 80) return {error:'We couldn’t extract usable text from this document.',name:file.name,size:prettySize(file.size),format,text}; return {name:file.name,size:prettySize(file.size),format,text}; }
function prettySize(n) { return n < 1024*1024 ? `${Math.max(1,Math.round(n/1024))} KB` : `${(n/1024/1024).toFixed(1)} MB`; }

function bind() {
  document.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',()=>setPage(el.dataset.page)));
  document.querySelectorAll('[data-theme]').forEach(el=>el.addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('careerlens-theme',state.theme);renderApp();}));
  document.querySelectorAll('[data-demo]').forEach(el=>el.addEventListener('click',()=>{state.analysis=buildAnalysis(demo.resumeText,demo.jdText,demo); state.page='processing'; state.processing=0; renderApp(); runProcessing();}));
  document.querySelectorAll('[data-file]').forEach(el=>el.addEventListener('change',async e=>{const file=e.target.files[0]; if(!file)return; state[e.target.dataset.file]=await parseFile(file); renderApp();}));
  const textarea=document.querySelector('[data-jd-text]'); if(textarea) textarea.addEventListener('input',e=>{const text=e.target.value; state.jd=text.trim()?{name:'Pasted job description',size:`${text.length} characters`,format:'TEXT',text,error:text.trim().length<80?'Add a fuller role description with requirements.':''}:null;});
  document.querySelectorAll('[data-clear]').forEach(el=>el.addEventListener('click',()=>{state[el.dataset.clear]=null;renderApp();}));
  document.querySelectorAll('[data-begin]').forEach(el=>el.addEventListener('click',()=>{if(!state.resume||!state.jd||state.resume.error||state.jd.error)return toastMessage('Both documents need usable text before analysis.');state.analysis=buildAnalysis(state.resume.text,state.jd.text,demo);state.page='processing';state.processing=0;renderApp();runProcessing();}));
  document.querySelectorAll('[data-filter]').forEach(el=>el.addEventListener('click',()=>{state.filter=el.dataset.filter;renderApp();}));
  document.querySelectorAll('[data-select]').forEach(el=>el.addEventListener('click',()=>{state.selected=Number(el.dataset.select);renderApp();}));
  document.querySelectorAll('[data-prepared]').forEach(el=>el.addEventListener('click',()=>{el.innerHTML=`Prepared ${icon('check',16)}`;el.classList.add('prepared');toastMessage('Question marked as familiar.');}));
  document.querySelectorAll('[data-export]').forEach(el=>el.addEventListener('click',exportReport));
  const mobile=document.querySelector('[data-mobile-menu]'); if(mobile) mobile.addEventListener('click',()=>document.querySelector('aside').classList.toggle('open'));
}
function runProcessing() { const advance=()=>{if(state.page!=='processing') return;if(state.processing>=7){setPage('overview');toastMessage('Analysis complete — your preparation plan is ready.');return;}state.processing++;renderApp();setTimeout(advance,420);};setTimeout(advance,420); }
function exportReport() { const a=getAnalysis(); const content=`CAREERLENS — ROLE ANALYSIS\n\nRole: ${a.role}\nCompany: ${a.company}\nAlignment: ${a.score}/100\n\nREQUIREMENTS\n${a.requirements.map(x=>`- ${x.name}: ${x.status.toUpperCase()} — ${x.evidence}`).join('\n')}\n\nPREPARATION\n${a.questions.map((q,i)=>`${i+1}. ${q.question}\n   Prepare: ${q.prepare}`).join('\n')}`; const blob=new Blob([content],{type:'text/plain'}); const url=URL.createObjectURL(blob); const link=document.createElement('a');link.href=url;link.download='careerlens-analysis.txt';link.click();URL.revokeObjectURL(url);toastMessage('Report exported as a text document.'); }

renderApp();
